stages:
  - test

test_pipeline:
  stage: test
  script:
    - echo "í¾‰ Pipeline GitLab CI/CD ActivÃ© !"
    - echo "âœ… Projet: Architecture Microservices"
    - echo "í±¤ Auteur: Moise"
    - echo "íº€ CI/CD Maintenant OpÃ©rationnel"
    - echo "í³… Date: $(date)"
  only:
    - main
