apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: microservices
data:
  VITE_USER_SERVICE_URL: "http://user-service:3001"
  VITE_PRODUCT_SERVICE_URL: "http://product-service:3002"
  VITE_ORDER_SERVICE_URL: "http://order-service:3003"
  VITE_PAYMENT_SERVICE_URL: "http://payment-service:3004"
  VITE_NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
