apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  namespace: microservices
spec:
  selector:
    app: postgres-primary
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
