apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          # Assurez-vous que cette image est bien construite localement
          image: api-gateway-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          # Ajoutez ici les variables d'environnement nécessaires si votre API Gateway en a besoin
