apiVersion: v1
kind: Service
metadata:
  name: order-service-clusterip
  labels:
    app: order-service
spec:
  # Le sélecteur doit correspondre aux labels de vos Pods du Order Service
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 30003      # Le port du Service K8s
      targetPort: 30003 # Le port du conteneur
  type: ClusterIP
