apiVersion: v1
kind: Service
metadata:
  name: product-service-clusterip
  labels:
    app: product-service
spec:
  # Doit correspondre aux labels de vos Pods du Product Service
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 30002      # Le port du Service K8s (pour la communication interne)
      targetPort: 30002 # Le port sur lequel le conteneur du Pod écoute
  type: ClusterIP
