apiVersion: v1
kind: Service
metadata:
  name: user-service-clusterip
  labels:
    app: user-service
spec:
  # Doit correspondre aux labels des Pods de votre déploiement existant
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 30001      # Le port du Service K8s
      targetPort: 30001 # Le port du conteneur du Pod
  type: ClusterIP      # Communication interne
